services:
  backend:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: backend
    ports:
      - 8009:8000
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_PORT: ${DATABASE_PORT}
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      DATABASE_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      PGDATA: "/var/lib/postgresql/data"
    ports:
      - "5430:5432"
    volumes:
      - ./postgres/storage/postgresql-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres_user -d postgres_db" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped